// AUTO-GENERATED by scripts/sync-addresses.mjs from deployments/mainnet/*.json.
// Do not edit by hand - rerun `pnpm sync:addresses` after a redeploy.
import type { Address } from "viem";

export const MAINNET_ADDRESSES = {
  core: "0x9C61fDb84b54F500cDC5334DCDd428F733714D8d" as Address,
  uniBlocks: "0xA02747A15432Be9b3F656b8a7fF944CBbDC6A4ad" as Address,
  blocksSale: "0x738B80c1Ffe63fcfeD5671e195b833f4Ae129265" as Address,
  hook: "0xEA99fb46f41543f621d6AB715A49F28CA97c80cC" as Address,
  swapHelper: "0xf00d3e96DD2ad20181A90C9f12125c3F4310fC0D" as Address,
  lpLocker: "0xf3811084E930203eb4143BEfF27ceF47f45992e2" as Address,
  renderer: "0xd844a6De1607Ec3338315B36c5042F915fb43e00" as Address,
  metadata: "0x2e482635040B11b4789426BBaF5d1aAC66bC34E1" as Address,
} as const;

export type ContractName = keyof typeof MAINNET_ADDRESSES;

/** Canonical Uniswap v4 PoolManager on mainnet (from the hook deploy record). */
export const POOL_MANAGER = "0x000000000004444c5dc75cB358380D2e3dE08A90" as Address;

/** Official v4 PoolKey recorded at deploy (currency0 = native ETH). */
export const OFFICIAL_POOL_KEY = {
  currency0: "0x0000000000000000000000000000000000000000" as Address,
  currency1: MAINNET_ADDRESSES.uniBlocks,
  fee: 3000,
  tickSpacing: 60,
  hooks: MAINNET_ADDRESSES.hook,
} as const;
